
repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.9.1
    hooks:
    - id: nbstripout
      files: ".ipynb"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict # Check for files that contain merge conflict strings.
    -   id: check-added-large-files # Prevent large files from being added to the repository.
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.5.1
    hooks:
    - id: black
  - repo: https://github.com/pycqa/isort
    rev: 9.0.1
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/jsh9/pydoclint
    rev: 0.9.1
    hooks:
    - id: pydoclint
      args: [--style=google, --check-return-types=False]
